### ISSUE TITLE
Please what is the purpose of this ping that runs every few seconds?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [findmypast-oss/mssqlex#21]
Please what is the purpose of this ping that runs every few seconds?

https://github.com/findmypast-oss/mssqlex/blob/d1b1253d3df7935377a6a4974f1dfe5803e6d512/lib/mssqlex/protocol.ex#L309-L317

**Comment by shdblowers** [comment]
This is part of our implementation of the [DBConnection behaviour](https://hexdocs.pm/db_connection/DBConnection.html).

In their documentation they say the following about `ping/1`:

> Called when the connection has been idle for a period of time. Return `{:ok, state}` to continue or `{:disconnect, exception, state}` to disconnect.
> 
> This callback is called if no callbacks have been called after the idle timeout and a client process is not using the state. The idle timeout can be configured by the `:idle_timeout` option. This function can be called whether the connection is checked in or checked out.
> 
> This callback is called in the connection process.
